services:
  - type: web
    name: convergence-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
